print("Hello")
print("World")
print("Intel Core i9 9900XE")
print("Table")
print("Sofa")
print("Tv")
print("Kitchen")
print("Bank")
print("Bottle")
print("Water")
print("Apple")
print("Banana")
print("Dollar")
print("Samsung 990 Pro")
print("Radeon 9070 Xt")
print("Red")
print("Green")
print("Blue")
print("White")
print("Black")